FROM ruby:2.4.0

# Install prerequisites
RUN \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs socat && \
  apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

