version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    pid: host
    command: /bin/sh -c 'cd /src && bundle && ./docker-fwd.sh && ./bin/rake db:setup && ./bin/rails s'
    links:
      - db
    volumes:
      - .:/src
      - bundle:/usr/local/bundle
    # command: bundle exec rake surveys:worker

  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD:
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  bundle:
