twilio:
  sid:
  token:
  phone_number: "+1..."
verboice:
  url: http://verboice.instedd.org
  project: 1
resmap:
  host: resourcemap.instedd.org
  user:
  pass:
  collection_id:
basic_auth:
  username: admin
  password: admin
